
// const mac = navigator.userAgent.includes('Macintosh');

// ⌥ ⌘ ⇧ ^ ↵
export const keyboardData = [
    [
        { n: 'ESC', mr: 60, c: 'Escape', kc: 27 },
        { n: 'F1', c: 'F1', kc: 112 },
        { n: 'F2', c: 'F2', kc: 113 },
        { n: 'F3', c: 'F3', kc: 114 },
        { n: 'F4', mr: 30, c: 'F4', kc: 115 },
        { n: 'F5', c: 'F5', kc: 116 },
        { n: 'F6', c: 'F6', kc: 117 },
        { n: 'F7', c: 'F7', kc: 118 },
        { n: 'F8', mr: 30, c: 'F8', kc: 119 },
        { n: 'F9', c: 'F9', kc: 120 },
        { n: 'F10', c: 'F10', kc: 121 },
        { n: 'F11', c: 'F11', kc: 122 },
        { n: 'F12', mr: 10, c: 'F12', kc: 123 },
        { n: 'SysRq', sn: 'PrtSc', c: 'F13', kc: 124 },
        { n: 'ScrLk' },
        { n: 'Break', sn: 'Pause', mr: 10 }
    ],
    [
        { n: '`', sn: '~', c: 'Backquote', kc: 192 },
        { n: '1', c: 'Digit1', kc: 49 },
        { n: '2', sn: '@', c: 'Digit2', kc: 50 },
        { n: '3', sn: '#', c: 'Digit3', kc: 51 },
        { n: '4', sn: '$', c: 'Digit4', kc: 52 },
        { n: '5', sn: '%', c: 'Digit5', kc: 53 },
        { n: '6', sn: '^', c: 'Digit6', kc: 54 },
        { n: '7', sn: '&', c: 'Digit7', kc: 55 },
        { n: '8', sn: '*', c: 'Digit8', kc: 56 },
        { n: '9', sn: '(', c: 'Digit9', kc: 57 },
        { n: '0', sn: ')', c: 'Digit0', kc: 48 },
        { n: '-', sn: '_', c: 'Minus', kc: 189 },
        { n: '=', sn: '+', c: 'Equal', kc: 187 },
        { n: '<-', 'w': 110, sn: '', mr: 10, c: 'Backspace', kc: 8 },
        { n: 'Ins', c: 'Insert', kc: 45 },
        { n: 'Home', c: 'Home', kc: 36 },
        { n: 'PgUp', mr: 10, c: 'PageUp', kc: 33 },
        { n: 'NumLk', c: 'NumLock', kc: 144 },
        { n: '/', c: 'NumpadDivide', kc: 111 },
        { n: '*', c: 'NumpadMultiply', kc: 106 },
        { n: '-', c: 'NumpadSubtract', kc: 109 }
    ],
    [
        { n: 'Tab', 'w': 80, c: 'Tab', kc: 9 },
        { n: 'Q', c: 'KeyQ', kc: 81 },
        { n: 'W', sn: '', c: 'KeyW', kc: 87 },
        { n: 'E', sn: '', c: 'KeyE', kc: 69 },
        { n: 'R', sn: '', c: 'KeyR', kc: 82 },
        { n: 'T', sn: '', c: 'KeyT', kc: 84 },
        { n: 'Y', sn: '', c: 'KeyY', kc: 89 },
        { n: 'U', sn: '', c: 'KeyU', kc: 85 },
        { n: 'I', sn: '', c: 'KeyI', kc: 73 },
        { n: 'O', sn: '', c: 'KeyO', kc: 79 },
        { n: 'P', sn: '', c: 'KeyP', kc: 80 },
        { n: '[', sn: '{', c: 'BracketLeft', kc: 219 },
        { n: ']', sn: '}', c: 'BracketRight', kc: 221 },
        { n: '\\', sn: '|', 'w': 80, sn: '', mr: 10, c: 'Backslash', kc: 220 },
        { n: 'Del', c: 'Delete', kc: 46 },
        { n: 'End', c: 'End', kc: 35 },
        { n: 'PgDn', mr: 10, c: 'PageDown', kc: 34 },
        { n: '7', sn: 'Home', c: 'Numpad7', kc: 103 },
        { n: '8', sn: '↑', c: 'Numpad8', kc: 104 },
        { n: '9', sn: 'PgUp', c: 'Numpad9', kc: 105 },
        { n: '+', tw: true, c: 'NumpadAdd', kc: 107 }
    ],
    [
        { n: 'Caps Lock', 'w': 110, c: 'CapsLock', kc: 20 },
        { n: 'A', c: 'KeyA', kc: 65 },
        { n: 'S', sn: '', c: 'KeyS', kc: 83 },
        { n: 'D', sn: '', c: 'KeyD', kc: 68 },
        { n: 'F', sn: '', c: 'KeyF', kc: 70 },
        { n: 'G', sn: '', c: 'KeyG', kc: 71 },
        { n: 'H', sn: '', c: 'KeyH', kc: 72 },
        { n: 'J', sn: '', c: 'KeyJ', kc: 74 },
        { n: 'K', sn: '', c: 'KeyK', kc: 75 },
        { n: 'L', sn: '', c: 'KeyL', kc: 76 },
        { n: ';', sn: ':', c: 'Semicolon', kc: 186 },
        { n: '\'', sn: '"', c: 'Quote', kc: 222 },
        { n: 'Enter', sn: '', 'w': 110, mr: 200, c: 'Enter', kc: 13 },
        { n: '4', sn: '←', c: 'Numpad4', kc: 100 },
        { n: '5', sn: ' ', c: 'Numpad5', kc: 101 },
        { n: '6', sn: '→', c: 'Numpad6', kc: 102 }
    ],
    [
        { n: 'Shift', 'w': 140, c: 'ShiftLeft', kc: 16 },
        { n: 'Z', c: 'KeyZ', kc: 90 },
        { n: 'X', sn: '', c: 'KeyX', kc: 88 },
        { n: 'C', sn: '', c: 'KeyC', kc: 67 },
        { n: 'V', sn: '', c: 'KeyV', kc: 86 },
        { n: 'B', sn: '', c: 'KeyB', kc: 66 },
        { n: 'N', sn: '', c: 'KeyN', kc: 78 },
        { n: 'M', sn: '', c: 'KeyM', kc: 77 },
        { n: ',', sn: '<', c: 'Comma', kc: 188 },
        { n: '.', sn: '>', c: 'Period', kc: 190 },
        { n: '/', sn: '?', c: 'Slash', kc: 191 },
        { n: 'Shift', sn: '', mr: 70, 'w': 140, c: 'ShiftRight', kc: 16 },
        { n: '↑', sn: '', mr: 70, c: 'ArrowUp', kc: 38 },
        { n: '1', sn: 'End', c: 'Numpad1', kc: 97 },
        { n: '2', sn: '↓', c: 'Numpad2', kc: 98 },
        { n: '3', sn: 'PgDn', c: 'Numpad3', kc: 99 },
        { n: 'Enter', tw: true, c: 'NumpadEnter', kc: 13 }
    ],
    [
        { n: 'Ctrl', c: 'ControlLeft', kc: 17 },
        { n: 'Win', c: 'MetaLeft', kc: 91 },
        { n: 'Alt', sn: '', c: 'AltLeft', kc: 18 },
        { n: 'Space', sn: '', 'w': 470, c: 'Space', kc: 32 },
        { n: 'Alt', sn: '', c: 'AltRight', kc: 18 },
        { n: 'Fn', sn: '' },
        { n: 'Ctx', sn: '', c: 'ContextMenu', kc: 93 },
        { n: 'Ctrl', sn: '', mr: 10, c: 'ControlRight', kc: 17 },
        { n: '←', sn: '', c: 'ArrowLeft', kc: 37 },
        { n: '↓', sn: '', c: 'ArrowDown', kc: 40 },
        { n: '→', sn: '', mr: 10, c: 'ArrowRight', kc: 39 },
        { n: '0', sn: 'Ins', 'w': 110, c: 'Numpad0', kc: 96 },
        { n: '.', sn: 'Del', c: 'NumpadDecimal', kc: 110 }
    ]
];